insert into m_lib_icpc_grouper values (1,"A01","PAIN,  GENERAL/MULTIPLE SITES");
insert into m_lib_icpc_grouper values (2,"A02","CHILLS");
insert into m_lib_icpc_grouper values (3,"A03","FEVER");
insert into m_lib_icpc_grouper values (4,"A04","WEAKNESS/TIREDNESS GENERAL");
insert into m_lib_icpc_grouper values (5,"A05","FEELING ILL");
insert into m_lib_icpc_grouper values (6,"A06","FAINTING/SYNCOPE");
insert into m_lib_icpc_grouper values (7,"A07","COMA");
insert into m_lib_icpc_grouper values (8,"A08","SWELLING");
insert into m_lib_icpc_grouper values (9,"A09","SWEATING PROBLEMS");
insert into m_lib_icpc_grouper values (10,"A10","BLEEDING, HAEMORRHAGE NOS");
insert into m_lib_icpc_grouper values (11,"A11","PAIN, CHEST NOS");
insert into m_lib_icpc_grouper values (12,"A13","CONCERN/FEAR, TREATMENT");
insert into m_lib_icpc_grouper values (13,"A16","IRRITABLE INFANT");
insert into m_lib_icpc_grouper values (14,"A18","CONCERN, APPEARANCE");
insert into m_lib_icpc_grouper values (15,"A20","EUTHANASIA REQUEST/DISCUSS");
insert into m_lib_icpc_grouper values (16,"A21","RISK FACTOR, MALIGNANCY");
insert into m_lib_icpc_grouper values (17,"A23","RISK FACTOR NOS");
insert into m_lib_icpc_grouper values (18,"A25","FEAR, DEATH, DYING");
insert into m_lib_icpc_grouper values (19,"A26","FEAR, CANCER NOS");
insert into m_lib_icpc_grouper values (20,"A27","FEAR, OTHER DISEASE, NOS");
insert into m_lib_icpc_grouper values (21,"A28","LIMITED FUNCTN/DISABIL NOS");
insert into m_lib_icpc_grouper values (22,"A29","GENERAL SYMPT/COMPL, OTHER");
insert into m_lib_icpc_grouper values (23,"A30","MED EXAM/CHECK, FULL, NOS");
insert into m_lib_icpc_grouper values (24,"A31","MED EXAM/CHECKUP, PART, NOS");
insert into m_lib_icpc_grouper values (25,"A44","PREVENTIVE IMMUNISATION GENERAL");
insert into m_lib_icpc_grouper values (26,"A70","TUBERCULOSIS");
insert into m_lib_icpc_grouper values (27,"A71","MEASLES");
insert into m_lib_icpc_grouper values (28,"A72","CHICKENPOX");
insert into m_lib_icpc_grouper values (29,"A73","MALARIA");
insert into m_lib_icpc_grouper values (30,"A74","RUBELLA");
insert into m_lib_icpc_grouper values (31,"A75","INFECTIOUS MONONUCLEOSIS");
insert into m_lib_icpc_grouper values (32,"A76","VIRAL EXANTHEM, OTHER");
insert into m_lib_icpc_grouper values (33,"A77","VIRAL DISEASE, OTHER/NOS");
insert into m_lib_icpc_grouper values (34,"A78","INFECTIOUS DISEASE, OTHER/NOS");
insert into m_lib_icpc_grouper values (35,"A79","MALIGNANCY NOS");
insert into m_lib_icpc_grouper values (36,"A80","TRAUMA/INJURY, NOS");
insert into m_lib_icpc_grouper values (37,"A81","MULTIPLE TRAUMA/INJURIES");
insert into m_lib_icpc_grouper values (38,"A82","SECONDARY EFFECT OF TRAUMA");
insert into m_lib_icpc_grouper values (39,"A84","POISONING BY MEDICAL AGENT");
insert into m_lib_icpc_grouper values (40,"A85","ADVERSE EFFECT MEDICAL AGENT");
insert into m_lib_icpc_grouper values (41,"A86","TOXIC EFFECT NON MEDICAL SUBST");
insert into m_lib_icpc_grouper values (42,"A87","COMPLICATION OF TREATMENT");
insert into m_lib_icpc_grouper values (43,"A88","ADVERSE EFFECT PHYSICAL FACTOR");
insert into m_lib_icpc_grouper values (44,"A89","EFFECTS PROSTHETIC DEVICE");
insert into m_lib_icpc_grouper values (45,"A90","CONGEN ANOMOLY NOS/MULTIPLE");
insert into m_lib_icpc_grouper values (46,"A91","ABNORMAL RESULTS INVESTIGATION");
insert into m_lib_icpc_grouper values (47,"A92","ALLERGY/ALLERGIC REACTION NOS");
insert into m_lib_icpc_grouper values (48,"A93","PREMATURE NEWBORN");
insert into m_lib_icpc_grouper values (49,"A94","PERINATAL MORBIDITY, OTHER");
insert into m_lib_icpc_grouper values (50,"A95","PERINATAL MORTALITY");
insert into m_lib_icpc_grouper values (51,"A96","DEATH");
insert into m_lib_icpc_grouper values (52,"A97","NO DISEASE");
insert into m_lib_icpc_grouper values (53,"A98","HEALTH MAINTAIN/PREVENT, OTHER");
insert into m_lib_icpc_grouper values (54,"A99","GENERAL DISEASE NOS");
insert into m_lib_icpc_grouper values (55,"B02","PAINFUL/ENLARGED LYMPH GLAND(S");
insert into m_lib_icpc_grouper values (56,"B04","BLOOD SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (57,"B25","FEAR, AIDS");
insert into m_lib_icpc_grouper values (58,"B26","FEAR, CANCER BLOOD/LYMPH");
insert into m_lib_icpc_grouper values (59,"B27","FEAR, BLOOD/LYMPH DISEASE, OTH");
insert into m_lib_icpc_grouper values (60,"B28","LIMITED FUNCTN/DISABIL BLOOD");
insert into m_lib_icpc_grouper values (61,"B29","BLOOD/IMMUNE  SYMPTOM");
insert into m_lib_icpc_grouper values (62,"B30","MED EXAM/CHECK, FULL, BLOOD");
insert into m_lib_icpc_grouper values (63,"B31","MED EXAM/CHECK, PART, BLOOD");
insert into m_lib_icpc_grouper values (64,"B70","LYMPHADENITIS, ACUTE");
insert into m_lib_icpc_grouper values (65,"B71","LYMPHADENITIS, NON-SPECIFIC");
insert into m_lib_icpc_grouper values (66,"B72","HODGKIN'S DISEASE/LYMPHOMAS");
insert into m_lib_icpc_grouper values (67,"B73","LEUKAEMIA");
insert into m_lib_icpc_grouper values (68,"B74","MALIGNT NEOPLASM BLOOD, OTHE");
insert into m_lib_icpc_grouper values (69,"B75","BENIGN/UNCERT NEOPL BLOOD/LYMP");
insert into m_lib_icpc_grouper values (70,"B76","RUPTURED SPLEEN, TRAUMATIC");
insert into m_lib_icpc_grouper values (71,"B77","INJURY BLOOD/LYMPH/SPLEEN, OTHE");
insert into m_lib_icpc_grouper values (72,"B78","ANAEMIAS, HEREDITARY HAEMOLYTIC");
insert into m_lib_icpc_grouper values (73,"B79","CONGENITAL ANOM BLOOD/LYMPH");
insert into m_lib_icpc_grouper values (74,"B80","ANAEMIA, IRON DEFICIENCY");
insert into m_lib_icpc_grouper values (75,"B81","ANAEMIA, VIT B12/FOLATE DEFICIENCY");
insert into m_lib_icpc_grouper values (76,"B82","ANAEMIA, OTHER/UNSPECIFIED");
insert into m_lib_icpc_grouper values (77,"B83","PURPURA/COAGULATION DEFECTS");
insert into m_lib_icpc_grouper values (78,"B84","ABNORMAL WHITE CELLS");
insert into m_lib_icpc_grouper values (79,"B87","SPLENOMEGALY");
insert into m_lib_icpc_grouper values (80,"B90","HIV-INFECTION, AIDS");
insert into m_lib_icpc_grouper values (81,"B99","BLOOD/LYMPH/SPLEEN DISEASE, OTH");
insert into m_lib_icpc_grouper values (82,"D01","PAIN/CRAMPS, ABDOMIN GENERAL");
insert into m_lib_icpc_grouper values (83,"D02","PAIN, ABDOMINAL EPIGASTRIC");
insert into m_lib_icpc_grouper values (84,"D03","HEARTBURN");
insert into m_lib_icpc_grouper values (85,"D04","PAIN, RECTAL/ANAL");
insert into m_lib_icpc_grouper values (86,"D05","PERIANAL ITCHING");
insert into m_lib_icpc_grouper values (87,"D06","PAIN, ABDOMINAL LOCALISED, OTHER");
insert into m_lib_icpc_grouper values (88,"D07","DYSPEPSIA/INDIGESTION");
insert into m_lib_icpc_grouper values (89,"D08","FLATULENCE/GAS/BELCHING");
insert into m_lib_icpc_grouper values (90,"D09","NAUSEA");
insert into m_lib_icpc_grouper values (811,"D10","VOMITING");
insert into m_lib_icpc_grouper values (91,"D11","DIARRHOEA");
insert into m_lib_icpc_grouper values (92,"D12","CONSTIPATION");
insert into m_lib_icpc_grouper values (93,"D13","JAUNDICE");
insert into m_lib_icpc_grouper values (94,"D14","HAEMATEMESIS/VOMITING BLOOD");
insert into m_lib_icpc_grouper values (95,"D15","MELAENA");
insert into m_lib_icpc_grouper values (96,"D16","RECTAL BLEEDING");
insert into m_lib_icpc_grouper values (97,"D17","INCONTINENCE OF BOWEL");
insert into m_lib_icpc_grouper values (98,"D18","CHANGE FAECES/BOWEL MOVEMENT");
insert into m_lib_icpc_grouper values (99,"D19","TEETH/GUM SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (100,"D20","MOUTH/TONGUE/LIP SYMPT/COMPL");
insert into m_lib_icpc_grouper values (101,"D21","SWALLOWING PROBLEMS");
insert into m_lib_icpc_grouper values (102,"D23","HEPATOMEGALY");
insert into m_lib_icpc_grouper values (103,"D24","ABDOMINAL MASS NOS");
insert into m_lib_icpc_grouper values (104,"D25","ABDOMINAL DISTENSION");
insert into m_lib_icpc_grouper values (105,"D26","FEAR, CANCER DIGESTIVE SYSTEM");
insert into m_lib_icpc_grouper values (106,"D27","FEAR, DIGESTIVE DISEASE, OTHER");
insert into m_lib_icpc_grouper values (107,"D28","LIMITED FUNCTN/DISABIL DIGEST");
insert into m_lib_icpc_grouper values (108,"D29","SYMPT/COMPLAINT, DIGESTIVE");
insert into m_lib_icpc_grouper values (109,"D30","MED EXAM/CHECK, FULL, DIGESTIVE");
insert into m_lib_icpc_grouper values (110,"D31","MED EXAM/CHECK, PART, DIGESTIVE");
insert into m_lib_icpc_grouper values (111,"D44","PREVENT IMMUNISE/VACC, DIGEST");
insert into m_lib_icpc_grouper values (112,"D70","GASTROINTESTINAL INFECTION");
insert into m_lib_icpc_grouper values (113,"D71","MUMPS");
insert into m_lib_icpc_grouper values (114,"D72","VIRAL HEPATITIS");
insert into m_lib_icpc_grouper values (115,"D73","GASTROENTERITIS PRESUM INFECT");
insert into m_lib_icpc_grouper values (116,"D74","MALIGNT NEOPLASM STOMACH");
insert into m_lib_icpc_grouper values (117,"D75","MALIGNT NEOPLASM COLON/RECTUM");
insert into m_lib_icpc_grouper values (118,"D76","MALIGNT NEOPLASM PANCREAS");
insert into m_lib_icpc_grouper values (119,"D77","MALIGNT NEOPLASM DIGEST OTHER");
insert into m_lib_icpc_grouper values (120,"D78","BENIGN/UNCERT NEOPLASM DIGEST");
insert into m_lib_icpc_grouper values (121,"D79","FOREIGN BODY IN DIGESTIVE SYST");
insert into m_lib_icpc_grouper values (122,"D80","INJURY DIGESTIVE SYSTEM, OTHER");
insert into m_lib_icpc_grouper values (123,"D81","CONGENITAL ANOMALY DIGESTIVE");
insert into m_lib_icpc_grouper values (124,"D82","TEETH/GUM DISEASE");
insert into m_lib_icpc_grouper values (125,"D83","MOUTH/TONGUE/LIP DISEASE");
insert into m_lib_icpc_grouper values (126,"D84","OESOPHAGUS DISEASE");
insert into m_lib_icpc_grouper values (127,"D85","DUODENAL ULCER");
insert into m_lib_icpc_grouper values (128,"D86","PEPTIC ULCERS, OTHER");
insert into m_lib_icpc_grouper values (129,"D87","STOMACH FUNCTION DISORDER");
insert into m_lib_icpc_grouper values (130,"D88","APPENDICITIS");
insert into m_lib_icpc_grouper values (131,"D89","INGUINAL HERNIA");
insert into m_lib_icpc_grouper values (132,"D90","HIATUS HERNIA");
insert into m_lib_icpc_grouper values (133,"D91","ABDOMINAL HERNIA, OTHER");
insert into m_lib_icpc_grouper values (134,"D92","DIVERTICULAR DISEASE");
insert into m_lib_icpc_grouper values (135,"D93","IRRITABLE BOWEL SYNDROME");
insert into m_lib_icpc_grouper values (136,"D94","CHRONIC ENTERITIS/ULCERATIVE COL");
insert into m_lib_icpc_grouper values (137,"D95","ANAL FISSURE/PERIANAL ABSCESS");
insert into m_lib_icpc_grouper values (138,"D96","WORMS/OTHER PARASITES");
insert into m_lib_icpc_grouper values (812,"D97","LIVER DISEASE NOS");
insert into m_lib_icpc_grouper values (139,"D98","CHOLECYSTITIS, CHOLELITHIASIS");
insert into m_lib_icpc_grouper values (140,"D99","DISEASE, DIGESTIVE, OTHER");
insert into m_lib_icpc_grouper values (141,"F01","PAIN, EYE");
insert into m_lib_icpc_grouper values (142,"F02","RED EYE");
insert into m_lib_icpc_grouper values (143,"F03","EYE DISCHARGE");
insert into m_lib_icpc_grouper values (144,"F04","VISUAL FLOATERS/SPOTS");
insert into m_lib_icpc_grouper values (145,"F05","VISUAL DISTURBANCE, OTHER");
insert into m_lib_icpc_grouper values (146,"F13","EYE SENSATIONS ABNORMAL");
insert into m_lib_icpc_grouper values (147,"F14","EYE MOVEMENTS ABNORMAL");
insert into m_lib_icpc_grouper values (148,"F15","EYE APPEARANCE ABNORMAL");
insert into m_lib_icpc_grouper values (149,"F16","EYELID SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (150,"F17","GLASSES SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (151,"F18","CONTACT LENS SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (152,"F27","FEAR, EYE DISEASE");
insert into m_lib_icpc_grouper values (153,"F28","LIMITED FUNCTN/DISABIL EYE");
insert into m_lib_icpc_grouper values (154,"F29","EYE SYMPT/COMPLAINT, OTHER");
insert into m_lib_icpc_grouper values (155,"F30","MED EXAM/CHECK, FULL, EYE");
insert into m_lib_icpc_grouper values (156,"F31","MED EXAM/CHECK, PART, EYE");
insert into m_lib_icpc_grouper values (157,"F70","CONJUNCTIVITIS, INFECTIOUS");
insert into m_lib_icpc_grouper values (158,"F71","CONJUNCTIVITIS, ALLERGIC");
insert into m_lib_icpc_grouper values (159,"F72","BLEPHARITIS/STYE/CHALAZION");
insert into m_lib_icpc_grouper values (160,"F73","EYE INFECTIONS/INFLAMM, OTHER");
insert into m_lib_icpc_grouper values (813,"F74","NEOPLASM OF EYE/ADNEXA");
insert into m_lib_icpc_grouper values (161,"F75","CONTUSION/ABRASIONS EYE");
insert into m_lib_icpc_grouper values (162,"F76","FOREIGN BODY IN EYE");
insert into m_lib_icpc_grouper values (163,"F79","INJURY EYE, OTHER");
insert into m_lib_icpc_grouper values (164,"F80","BLOCKED LACRIMAL DUCT, INFANT");
insert into m_lib_icpc_grouper values (814,"F81","CONGENITAL ANOMALY EYE OTHER");
insert into m_lib_icpc_grouper values (165,"F82","DETACHED RETINA");
insert into m_lib_icpc_grouper values (166,"F83","RETINOPATHY");
insert into m_lib_icpc_grouper values (167,"F84","MACULAR DEGENERATION");
insert into m_lib_icpc_grouper values (168,"F85","CORNEAL ULCER (INCL HERPETIC)");
insert into m_lib_icpc_grouper values (815,"F86","TRACHOMA");
insert into m_lib_icpc_grouper values (169,"F91","REFRACTIVE ERROR");
insert into m_lib_icpc_grouper values (170,"F92","CATARACT");
insert into m_lib_icpc_grouper values (171,"F93","GLAUCOMA");
insert into m_lib_icpc_grouper values (172,"F94","BLINDNESS");
insert into m_lib_icpc_grouper values (173,"F95","STRABISMUS");
insert into m_lib_icpc_grouper values (174,"F99","EYE/ADNEXA DISEASE, OTHER");
insert into m_lib_icpc_grouper values (175,"G01","ABDOMINAL PAIN (ALL)");
insert into m_lib_icpc_grouper values (176,"G02","ANXIETY  (ALL)");
insert into m_lib_icpc_grouper values (177,"G03","ARTHRITIS ( EXCL OA  & RHEUMATOID)");
insert into m_lib_icpc_grouper values (178,"G04","BACK  COMPLAINTS (ALL)");
insert into m_lib_icpc_grouper values (179,"G05","CHECK-UPS (ALL)");
insert into m_lib_icpc_grouper values (180,"G06","CHECK-UPS GENERAL (ALL)");
insert into m_lib_icpc_grouper values (181,"G07","CHECK-UPS BLOOD (ALL)");
insert into m_lib_icpc_grouper values (182,"G08","CHECK-UPS DIGESTIVE (ALL)");
insert into m_lib_icpc_grouper values (183,"G09","CHECK-UPS EYE ( ALL)");
insert into m_lib_icpc_grouper values (184,"G10","CHECK-UPS EAR (ALL)");
insert into m_lib_icpc_grouper values (185,"G11","CHECK-UPS CARDIOVASCULAR (ALL)");
insert into m_lib_icpc_grouper values (186,"G12","CHECK-UPS MUSCULOSKELETAL (ALL)");
insert into m_lib_icpc_grouper values (187,"G13","CHECK-UPS NEUROLOGICAL (ALL)");
insert into m_lib_icpc_grouper values (188,"G14","CHECK-UPS PSYCHOLOGICAL (ALL)");
insert into m_lib_icpc_grouper values (189,"G15","CHECK-UPS RESPIRATORY (ALL)");
insert into m_lib_icpc_grouper values (190,"G16","CHECK-UPS SKIN (ALL)");
insert into m_lib_icpc_grouper values (191,"G17","ENDOCRINE/METABOLIC (ALL)");
insert into m_lib_icpc_grouper values (192,"G18","CHECK-UPS UROLOGICAL (ALL)");
insert into m_lib_icpc_grouper values (193,"G19","CHECK-UPS PRE/POSTNATAL ( ALL)");
insert into m_lib_icpc_grouper values (194,"G20","CHECK-UPS FEMALE GENITAL (ALL)");
insert into m_lib_icpc_grouper values (195,"G21","CHECK-UPS MALE GENITAL (ALL)");
insert into m_lib_icpc_grouper values (196,"G22","CHECK-UPS SOCIAL (ALL)");
insert into m_lib_icpc_grouper values (197,"G23","URINARY TRACT INFECTNS ( UTI) (ALL)");
insert into m_lib_icpc_grouper values (198,"G24","DEPRESSION (ALL)");
insert into m_lib_icpc_grouper values (786,"G25","HYPERTENSION/HIGH BP");
insert into m_lib_icpc_grouper values (199,"G26","HYPERTENSION (ALL)");
insert into m_lib_icpc_grouper values (200,"G27","IMMUNISATION/VACCINATION (ALL)");
insert into m_lib_icpc_grouper values (787,"G28","ORAL CONTRACEPTION");
insert into m_lib_icpc_grouper values (201,"G29","OSTEOARTHRITIS (ALL)");
insert into m_lib_icpc_grouper values (788,"G30","PREGNANCY (ALL)");
insert into m_lib_icpc_grouper values (789,"G31","PRESCRIPTION (ALL)");
insert into m_lib_icpc_grouper values (202,"G32","RASH (SKIN) (ALL)");
insert into m_lib_icpc_grouper values (203,"G33","SPRAIN/STRAINS (ALL)");
insert into m_lib_icpc_grouper values (204,"G34","SWELLING (SKIN) (ALL)");
insert into m_lib_icpc_grouper values (790,"G35","TEST RESULTS (ALL)");
insert into m_lib_icpc_grouper values (205,"G36","TONSILLITIS (ALL)");
insert into m_lib_icpc_grouper values (206,"G37","FRACTURES (ALL)");
insert into m_lib_icpc_grouper values (207,"G40","DIABETES (ALL)");
insert into m_lib_icpc_grouper values (208,"G42","ANAEMIA (ALL)");
insert into m_lib_icpc_grouper values (209,"G43","MENSTRUAL PROBLEMS (ALL)");
insert into m_lib_icpc_grouper values (210,"G44","ABNORMAL TEST RESULTS (ALL)");
insert into m_lib_icpc_grouper values (211,"G45","IHD (ALL)  (+/-ANGINA)");
insert into m_lib_icpc_grouper values (212,"G63","WEIGHT PROBLEMS (ALL)");
insert into m_lib_icpc_grouper values (213,"G64","VISUAL ACUITY PROBLEMS ( ALL)");
insert into m_lib_icpc_grouper values (214,"G66","ALLERGY (ALL)");
insert into m_lib_icpc_grouper values (215,"G67","ARTHRITIS (ALL INCL OA & RHEUMATOI)");
insert into m_lib_icpc_grouper values (216,"G68","BLOOD PRESSURE PROBLEMS (ALL)");
insert into m_lib_icpc_grouper values (760,"G69","CHECK-UPS (WORK)");
insert into m_lib_icpc_grouper values (217,"G70","NEOPLASMS BENIGN");
insert into m_lib_icpc_grouper values (218,"G71","NEOPLASMS MALIGNANT (ALL)");
insert into m_lib_icpc_grouper values (219,"G72","NEOPLASMS UNSPECIFIED");
insert into m_lib_icpc_grouper values (220,"G73","NEOPLASMS  UNCERTAIN NATURE (ALL)");
insert into m_lib_icpc_grouper values (221,"G74","NEOPLASMS (ALL)");
insert into m_lib_icpc_grouper values (222,"G75","DEAFNESS (ALL)");
insert into m_lib_icpc_grouper values (223,"G76","DEMENTIA ( ALL)");
insert into m_lib_icpc_grouper values (224,"G77","DIABETES (NON-GESTATIONAL)");
insert into m_lib_icpc_grouper values (225,"G78","HYPERTENSION  (NON-GESTATIONAL)");
insert into m_lib_icpc_grouper values (226,"G79","NEUROSES (ALL)");
insert into m_lib_icpc_grouper values (227,"G80","PSYCHOSES (ALL) ( INCL O.B.S)");
insert into m_lib_icpc_grouper values (228,"G81","RHINITIS ( ALL)");
insert into m_lib_icpc_grouper values (229,"G82","STDs (ALL)");
insert into m_lib_icpc_grouper values (230,"H01","PAIN, EAR/EARACHE (ALL)");
insert into m_lib_icpc_grouper values (231,"H02","HEARING COMPLAINT");
insert into m_lib_icpc_grouper values (232,"H03","TINNITUS, RINGING/BUZZING EAR");
insert into m_lib_icpc_grouper values (233,"H04","EAR DISCHARGE ( EXCL BLOOD)");
insert into m_lib_icpc_grouper values (234,"H05","BLEEDING EAR");
insert into m_lib_icpc_grouper values (235,"H13","PLUGGED FEELING EAR");
insert into m_lib_icpc_grouper values (236,"H15","CONCERN, APPEARANCE OF EAR");
insert into m_lib_icpc_grouper values (237,"H27","FEAR, EAR DISEASE");
insert into m_lib_icpc_grouper values (238,"H28","LIMITED FUNCTN/DISABIL EAR");
insert into m_lib_icpc_grouper values (239,"H29","EAR SYMPT/COMPLAINT, OTHER");
insert into m_lib_icpc_grouper values (240,"H30","MED EXAM/CHECK, FULL, EAR");
insert into m_lib_icpc_grouper values (241,"H31","MED EXAM/CHECK, PART, EAR");
insert into m_lib_icpc_grouper values (242,"H70","OTITIS EXTERNA");
insert into m_lib_icpc_grouper values (243,"H71","ACUTE OTITIS MEDIA/MYRINGITIS");
insert into m_lib_icpc_grouper values (244,"H72","SEROUS OTITIS MEDIA");
insert into m_lib_icpc_grouper values (245,"H73","EUSTACHIAN SALPINGITIS");
insert into m_lib_icpc_grouper values (246,"H74","CHRONIC OTITIS MEDIA");
insert into m_lib_icpc_grouper values (247,"H75","NEOPLASM EAR");
insert into m_lib_icpc_grouper values (248,"H76","FOREIGN BODY IN EAR");
insert into m_lib_icpc_grouper values (249,"H77","PERFORATION EAR DRUM");
insert into m_lib_icpc_grouper values (250,"H78","INJURY EAR, SUPERFICIAL");
insert into m_lib_icpc_grouper values (251,"H79","INJURY EAR, OTHER");
insert into m_lib_icpc_grouper values (252,"H80","CONGENITAL ANOMALY EAR");
insert into m_lib_icpc_grouper values (253,"H81","EXCESSIVE EAR WAX");
insert into m_lib_icpc_grouper values (254,"H82","VERTIGINOUS SYNDROMES");
insert into m_lib_icpc_grouper values (255,"H83","OTOSCLEROSIS");
insert into m_lib_icpc_grouper values (256,"H84","PRESBYACUSIS");
insert into m_lib_icpc_grouper values (257,"H85","ACOUSTIC TRAUMA");
insert into m_lib_icpc_grouper values (258,"H86","DEAFNESS");
insert into m_lib_icpc_grouper values (259,"H99","EAR/MASTOID DISEASE, OTHER");
insert into m_lib_icpc_grouper values (260,"K01","PAIN, HEART");
insert into m_lib_icpc_grouper values (261,"K02","PRESSURE/TIGHTNESS OF HEART");
insert into m_lib_icpc_grouper values (262,"K03","PAIN, CARDIOVASCULAR NOS");
insert into m_lib_icpc_grouper values (263,"K04","PALPITATIONS/AWARE  HEART");
insert into m_lib_icpc_grouper values (264,"K05","IRREGULAR HEARTBEAT, OTHER");
insert into m_lib_icpc_grouper values (265,"K06","PROMINENT VEINS");
insert into m_lib_icpc_grouper values (266,"K07","SWOLLEN ANKLES/OEDEMA");
insert into m_lib_icpc_grouper values (267,"K22","RISK FACTOR, CARDIOVASCULAR");
insert into m_lib_icpc_grouper values (268,"K24","FEAR, HEART DISEASE");
insert into m_lib_icpc_grouper values (269,"K25","FEAR, HYPERTENSION");
insert into m_lib_icpc_grouper values (270,"K27","FEAR, CARDIOVASCULAR DISEASE");
insert into m_lib_icpc_grouper values (271,"K28","LIMITED FUNCTN/DISABIL CARDIOVA");
insert into m_lib_icpc_grouper values (272,"K29","CARDIOVASCULAR SYMPT/COM, OTHE");
insert into m_lib_icpc_grouper values (273,"K30","MED EXAM/CHECK, FULL, CARDIOVA");
insert into m_lib_icpc_grouper values (274,"K31","MED EXAM/CHECK, PART, CARDIOVA");
insert into m_lib_icpc_grouper values (275,"K70","CARDIOVASCULAR SYSTEM INFECTIO");
insert into m_lib_icpc_grouper values (276,"K71","RHEUMATIC FEVER/HEART DISEASE");
insert into m_lib_icpc_grouper values (277,"K72","NEOPLASM CARDIOVASCULAR");
insert into m_lib_icpc_grouper values (278,"K73","CONGENITAL ANOM CARDIOVASCU");
insert into m_lib_icpc_grouper values (279,"K74","IHD WITH ANGINA");
insert into m_lib_icpc_grouper values (280,"K75","ACUTE MYOCARDIAL INFARCTION");
insert into m_lib_icpc_grouper values (281,"K76","IHD WITHOUT ANGINA");
insert into m_lib_icpc_grouper values (282,"K77","HEART FAILURE");
insert into m_lib_icpc_grouper values (283,"K78","ATRIAL FIBRILLATION/FLUTTER");
insert into m_lib_icpc_grouper values (284,"K79","PAROXYSMAL TACHYCARDIA");
insert into m_lib_icpc_grouper values (285,"K80","CARDIAC ARRHYTHMIA NOS");
insert into m_lib_icpc_grouper values (286,"K81","HEART/ARTERIAL MURMER NOS");
insert into m_lib_icpc_grouper values (287,"K82","PULMONARY HEART DISEASE");
insert into m_lib_icpc_grouper values (288,"K83","HEART VALVE DISEASE NOS");
insert into m_lib_icpc_grouper values (289,"K84","HEART DISEASE, OTHER");
insert into m_lib_icpc_grouper values (290,"K85","ELEVATED BLOOD PRESSURE");
insert into m_lib_icpc_grouper values (291,"K86","HYPERTENSION, UNCOMPLICATED");
insert into m_lib_icpc_grouper values (292,"K87","HYPERTENSION, COMPLICATED");
insert into m_lib_icpc_grouper values (293,"K88","POSTURAL HYPOTENSION (LOW BP");
insert into m_lib_icpc_grouper values (294,"K89","TRANSIENT CEREBRAL ISCHAEMIA");
insert into m_lib_icpc_grouper values (295,"K90","STROKE/CVA");
insert into m_lib_icpc_grouper values (296,"K91","CVD (EXCL HEART/BRAIN)");
insert into m_lib_icpc_grouper values (297,"K92","ATHEROSCLEROSIS/PVD");
insert into m_lib_icpc_grouper values (298,"K93","PULMONARY EMBOLISM");
insert into m_lib_icpc_grouper values (299,"K94","PHLEBITIS/THROMBOPHLEBITIS");
insert into m_lib_icpc_grouper values (300,"K95","VARICOSE VEINS OF LEG");
insert into m_lib_icpc_grouper values (301,"K96","HAEMORRHOIDS");
insert into m_lib_icpc_grouper values (302,"K99","CARDIOVASCULAR DISEASE, OTHER");
insert into m_lib_icpc_grouper values (303,"L01","NECK SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (304,"L02","BACK SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (305,"L03","LOW BACK SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (306,"L04","CHEST SYMPT/COMPL, MUSCULAR");
insert into m_lib_icpc_grouper values (307,"L05","FLANK/AXILLA SYMPT/COMPL");
insert into m_lib_icpc_grouper values (308,"L07","JAW SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (816,"L08","SHOULDER SYMPTOM/COMPLAINT");
insert into m_lib_icpc_grouper values (309,"L09","ARM SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (310,"L10","ELBOW SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (311,"L11","WRIST SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (312,"L12","HAND & FINGER SYMPT/COMPLAIN");
insert into m_lib_icpc_grouper values (313,"L13","HIP SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (314,"L14","LEG/THIGH SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (315,"L15","KNEE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (316,"L16","ANKLE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (317,"L17","FOOT & TOE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (318,"L18","PAIN, MUSCLE");
insert into m_lib_icpc_grouper values (319,"L19","MUSCLE SYMPT/COMPLAINT NOS");
insert into m_lib_icpc_grouper values (320,"L20","JOINT SYMPT/COMPLAINT NOS");
insert into m_lib_icpc_grouper values (321,"L26","FEAR, CANCER MUSCULOSKELETA");
insert into m_lib_icpc_grouper values (322,"L27","FEAR, MUSCULOSKELETAL DISEAS");
insert into m_lib_icpc_grouper values (323,"L28","LIMITED FUNCTN/DISABIL MUSCULO");
insert into m_lib_icpc_grouper values (324,"L29","MUSCULOSKELETAL SYMPT/COMPLA");
insert into m_lib_icpc_grouper values (325,"L30","MED EXAM/CHECK, FULL, MUSCULOS");
insert into m_lib_icpc_grouper values (326,"L31","MED EXAM/CHECK, PART, MUSCUL");
insert into m_lib_icpc_grouper values (327,"L70","MUSCULOSKELETAL INFECTION");
insert into m_lib_icpc_grouper values (328,"L71","MALIGNT NEOPLASM MUSCULOSKEL");
insert into m_lib_icpc_grouper values (329,"L72","FRACTURE, RADIUS/ULNA");
insert into m_lib_icpc_grouper values (330,"L73","FRACTURE, TIBIA/FIBULA");
insert into m_lib_icpc_grouper values (331,"L74","FRACTURE, HAND/FOOT BONE");
insert into m_lib_icpc_grouper values (332,"L75","FRACTURE, FEMUR");
insert into m_lib_icpc_grouper values (333,"L76","FRACTURE, OTHER");
insert into m_lib_icpc_grouper values (334,"L77","SPRAINS & STRAINS, ANKLE");
insert into m_lib_icpc_grouper values (335,"L78","SPRAINS & STRAINS, KNEE");
insert into m_lib_icpc_grouper values (336,"L79","SPRAINS & STRAINS, JOINTS NOS");
insert into m_lib_icpc_grouper values (337,"L80","DISLOCATION & SUBLUXATION");
insert into m_lib_icpc_grouper values (338,"L81","INJURY MUSCULOSKELETAL NOS");
insert into m_lib_icpc_grouper values (339,"L82","CONGENITAL ANOM MUSCULOSKEL");
insert into m_lib_icpc_grouper values (340,"L83","NECK SYNDROME (INCL ARTHRIT)");
insert into m_lib_icpc_grouper values (341,"L84","BACK SYNDROME, NO RADIATE PAIN");
insert into m_lib_icpc_grouper values (342,"L85","ACQUIRED DEFORMITY OF SPINE");
insert into m_lib_icpc_grouper values (343,"L86","BACK SYNDROME + RADIATING PAIN");
insert into m_lib_icpc_grouper values (344,"L87","BURSITIS/TENDONITIS/SYNOVITIS");
insert into m_lib_icpc_grouper values (345,"L88","RHEUMATOID ARTHRITIS");
insert into m_lib_icpc_grouper values (346,"L89","OSTEOARTHROSIS OF HIP");
insert into m_lib_icpc_grouper values (347,"L90","OSTEOARTHROSIS OF KNEE");
insert into m_lib_icpc_grouper values (348,"L91","OSTEOARTHROSIS, OTHER");
insert into m_lib_icpc_grouper values (349,"L92","SHOULDER SYNDROME (INCL ARTHRIT");
insert into m_lib_icpc_grouper values (350,"L93","TENNIS ELBOW");
insert into m_lib_icpc_grouper values (351,"L94","OSTEOCHONDROSIS");
insert into m_lib_icpc_grouper values (352,"L95","OSTEOPOROSIS");
insert into m_lib_icpc_grouper values (353,"L96","ACUTE INTERNAL DAMAGE KNEE");
insert into m_lib_icpc_grouper values (354,"L97","BENIGN/UNCERT NEOPL MUSCULOSKE");
insert into m_lib_icpc_grouper values (355,"L98","ACQUIRED DEFORMITY OF LIMB");
insert into m_lib_icpc_grouper values (356,"L99","MUSCULOSKELETAL DISEASE, OTHER");
insert into m_lib_icpc_grouper values (357,"N01","HEADACHE");
insert into m_lib_icpc_grouper values (358,"N03","PAIN, FACE");
insert into m_lib_icpc_grouper values (359,"N04","RESTLESS LEGS");
insert into m_lib_icpc_grouper values (360,"N05","TINGLING FINGERS/FEET/TOES");
insert into m_lib_icpc_grouper values (361,"N06","SENSATION DISTURBANCES, OTHER");
insert into m_lib_icpc_grouper values (362,"N07","CONVULSIONS/SEIZURES");
insert into m_lib_icpc_grouper values (363,"N08","ABNORMAL INVOLUNTARY MOVEMENTS");
insert into m_lib_icpc_grouper values (364,"N16","DISTURBANCE SMELL/TASTE");
insert into m_lib_icpc_grouper values (365,"N17","VERTIGO/DIZZINESS");
insert into m_lib_icpc_grouper values (366,"N18","PARALYSIS/WEAKNESS");
insert into m_lib_icpc_grouper values (367,"N19","SPEECH DISORDER");
insert into m_lib_icpc_grouper values (817,"N26","FEAR OF CANCER OF NEUROLOGICAL SYSTEM");
insert into m_lib_icpc_grouper values (818,"N27","FEAR OF NEUROLOGICAL DISEASE OTHER");
insert into m_lib_icpc_grouper values (819,"N28","LIMITED FUNCTION/DISABILITY NEUROLOGICAL");
insert into m_lib_icpc_grouper values (368,"N29","NEUROLOGICAL SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (369,"N30","MED EXAM/CHECK, FULL, NEUROLO");
insert into m_lib_icpc_grouper values (370,"N31","MED EXAM/CHECK, PART, NEUROL");
insert into m_lib_icpc_grouper values (371,"N44","PREVENT IMMUNISE/VACC, NEUROL");
insert into m_lib_icpc_grouper values (372,"N70","POLIOMYELITIS");
insert into m_lib_icpc_grouper values (373,"N71","MENINGITIS/ENCEPHALITIS");
insert into m_lib_icpc_grouper values (374,"N72","TETANUS");
insert into m_lib_icpc_grouper values (375,"N73","NEUROLOGICAL INFECTION, OTHER");
insert into m_lib_icpc_grouper values (376,"N74","MALIGNT NEOPLASM NERVOUS SYS");
insert into m_lib_icpc_grouper values (377,"N75","BENIGN NEOPLASM NERVOUS SYSTEM");
insert into m_lib_icpc_grouper values (378,"N76","NEOPLASM UNCERTAIN NEUROLOG)");
insert into m_lib_icpc_grouper values (379,"N79","CONCUSSION");
insert into m_lib_icpc_grouper values (380,"N80","INJURY HEAD, OTHER");
insert into m_lib_icpc_grouper values (381,"N81","INJURY NERVOUS SYSTEM, OTHER");
insert into m_lib_icpc_grouper values (382,"N85","CONGENITAL ANOM NEUROLOGICA");
insert into m_lib_icpc_grouper values (383,"N86","MULTIPLE SCLEROSIS");
insert into m_lib_icpc_grouper values (384,"N87","PARKINSONISM");
insert into m_lib_icpc_grouper values (385,"N88","EPILEPSY");
insert into m_lib_icpc_grouper values (386,"N89","MIGRAINE");
insert into m_lib_icpc_grouper values (387,"N90","CLUSTER HEADACHE");
insert into m_lib_icpc_grouper values (388,"N91","FACIAL PARALYSIS/BELL'S PALSY");
insert into m_lib_icpc_grouper values (389,"N92","TRIGEMINAL NEURALGIA");
insert into m_lib_icpc_grouper values (390,"N93","CARPAL TUNNEL SYNDROME");
insert into m_lib_icpc_grouper values (391,"N94","PERIPHERAL NEURITIS/NEUROPATHY");
insert into m_lib_icpc_grouper values (392,"N95","TENSION HEADACHE");
insert into m_lib_icpc_grouper values (393,"N99","NEUROLOGICAL DISEASE, OTHER");
insert into m_lib_icpc_grouper values (394,"P01","FEELING ANXIOUS/NERVOUS/TENSE");
insert into m_lib_icpc_grouper values (395,"P02","ACUTE STRESS REACTION");
insert into m_lib_icpc_grouper values (396,"P03","FEELING DEPRESSED");
insert into m_lib_icpc_grouper values (397,"P04","FEELING/BEHAVING IRRITABLE/ANG");
insert into m_lib_icpc_grouper values (398,"P05","SENILITY, FEELING/BEHAVING OLD");
insert into m_lib_icpc_grouper values (399,"P06","SLEEP DISTURBANCE");
insert into m_lib_icpc_grouper values (400,"P07","SEXUAL DESIRE REDUCED");
insert into m_lib_icpc_grouper values (401,"P08","SEXUAL FULFILMENT REDUCED");
insert into m_lib_icpc_grouper values (402,"P09","CONCERN, SEXUAL PREFERENC");
insert into m_lib_icpc_grouper values (403,"P10","STAMMERING, STUTTERING, TICS");
insert into m_lib_icpc_grouper values (404,"P11","EATING PROBLEMS IN CHILDREN");
insert into m_lib_icpc_grouper values (405,"P12","BEDWETTING, ENURESIS");
insert into m_lib_icpc_grouper values (406,"P13","ENCOPRESIS/BOWEL TRAIN PROB");
insert into m_lib_icpc_grouper values (407,"P15","CHRONIC ALCOHOL ABUSE");
insert into m_lib_icpc_grouper values (408,"P16","ACUTE ALCOHOL ABUSE");
insert into m_lib_icpc_grouper values (409,"P17","TOBACCO ABUSE");
insert into m_lib_icpc_grouper values (410,"P18","MEDICATION ABUSE");
insert into m_lib_icpc_grouper values (411,"P19","DRUG ABUSE");
insert into m_lib_icpc_grouper values (412,"P20","MEMORY DISTURBANCE");
insert into m_lib_icpc_grouper values (413,"P22","CHILD BEHAVIOR SYMPT/COMPL");
insert into m_lib_icpc_grouper values (414,"P23","ADOLESCENT BEHAVIOUR SYMPTOM/C");
insert into m_lib_icpc_grouper values (415,"P24","SPECIFIC LEARNING PROBLEM");
insert into m_lib_icpc_grouper values (416,"P25","PHASE OF LIFE PROBLEM IN ADULT");
insert into m_lib_icpc_grouper values (417,"P27","FEAR, MENTAL DISORDER");
insert into m_lib_icpc_grouper values (820,"P28","LIMITED FUNCTION/DISABILITY PSYCHOLOGICAL");
insert into m_lib_icpc_grouper values (418,"P29","PSYCHOLOGICAL SYMPT/COMPLAIN");
insert into m_lib_icpc_grouper values (419,"P30","MED EXAM/CHECK, FULL, PSYCHOL");
insert into m_lib_icpc_grouper values (420,"P31","MED EXAM/CHECK, PART, PSYCHOL");
insert into m_lib_icpc_grouper values (421,"P70","DEMENTIA (INCL SENILE, ALZHEIM");
insert into m_lib_icpc_grouper values (422,"P71","ORGANIC PSYCHOSIS, OTHER");
insert into m_lib_icpc_grouper values (423,"P72","SCHIZOPHRENIA");
insert into m_lib_icpc_grouper values (424,"P73","AFFECTIVE PSYCHOSIS");
insert into m_lib_icpc_grouper values (425,"P74","ANXIETY DISORDER/ANXIETY STATE");
insert into m_lib_icpc_grouper values (426,"P75","SOMATISATION DISORDER");
insert into m_lib_icpc_grouper values (427,"P76","DEPRESSIVE DISORDER");
insert into m_lib_icpc_grouper values (428,"P77","SUICIDE/SUICIDE ATTEMPT");
insert into m_lib_icpc_grouper values (429,"P78","NEURASTHENIA, SURMENAGE");
insert into m_lib_icpc_grouper values (430,"P79","PHOBIA, COMPULSIVE DISORDER");
insert into m_lib_icpc_grouper values (431,"P80","PERSONALITY DISORDER");
insert into m_lib_icpc_grouper values (432,"P81","HYPERKINETIC DISORDER");
insert into m_lib_icpc_grouper values (433,"P82","POST TRAUMATIC STRESS DISORDER");
insert into m_lib_icpc_grouper values (434,"P85","MENTAL RETARDATION");
insert into m_lib_icpc_grouper values (435,"P86","ANOREXIA NERVOSA, BULIMIA");
insert into m_lib_icpc_grouper values (436,"P98","PSYCHOSES NOS, OTHER");
insert into m_lib_icpc_grouper values (437,"P99","PSYCHOLOGICAL DISORDERS, OTHER");
insert into m_lib_icpc_grouper values (438,"R01","PAIN, RESPIRATORY SYSTEM");
insert into m_lib_icpc_grouper values (439,"R02","SHORT OF BREATH, DYSPNOEA");
insert into m_lib_icpc_grouper values (440,"R03","WHEEZING");
insert into m_lib_icpc_grouper values (441,"R04","BREATHING PROBLEMS, OTHER");
insert into m_lib_icpc_grouper values (442,"R05","COUGH");
insert into m_lib_icpc_grouper values (443,"R06","NOSE BLEED/EPISTAXIS");
insert into m_lib_icpc_grouper values (444,"R07","SNEEZING/NASAL CONGESTION");
insert into m_lib_icpc_grouper values (445,"R08","NOSE SYMPT/COMPLAINT, OTHER");
insert into m_lib_icpc_grouper values (446,"R09","SINUS SYMPT/COMPLAINT  (INCL");
insert into m_lib_icpc_grouper values (447,"R21","THROAT SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (448,"R23","VOICE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (449,"R24","HAEMOPTYSIS");
insert into m_lib_icpc_grouper values (450,"R25","SPUTUM/PHLEGM ABNORMAL");
insert into m_lib_icpc_grouper values (451,"R26","FEAR, CANCER  RESPIRATORY SYS");
insert into m_lib_icpc_grouper values (452,"R27","FEAR, RESPIRATORY DISEASE, OTH");
insert into m_lib_icpc_grouper values (453,"R28","LIMITED FUNCTN/DISABIL RESPIRA");
insert into m_lib_icpc_grouper values (454,"R29","RESPIRATORY SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (455,"R30","MED EXAM/CHECK, FULL, RESPIRAT");
insert into m_lib_icpc_grouper values (456,"R31","MED EXAM/CHECK, PART, RESPIRA");
insert into m_lib_icpc_grouper values (457,"R44","PREVENT IMMUNISE/VACC, REPIRAT");
insert into m_lib_icpc_grouper values (458,"R71","WHOOPING COUGH");
insert into m_lib_icpc_grouper values (459,"R72","STREP THROAT");
insert into m_lib_icpc_grouper values (460,"R73","BOIL, ABSCESS NOSE");
insert into m_lib_icpc_grouper values (461,"R74","URTI,  ACUTE");
insert into m_lib_icpc_grouper values (462,"R75","SINUSITIS ACUTE/CHRONIC");
insert into m_lib_icpc_grouper values (463,"R76","TONSILLITIS ACUTE");
insert into m_lib_icpc_grouper values (464,"R77","LARYNGITIS/TRACHEITIS, ACUTE");
insert into m_lib_icpc_grouper values (465,"R78","ACUTE BRONCHITIS/BRONCHIOLITIS");
insert into m_lib_icpc_grouper values (466,"R79","CHRONIC BRONCHITIS");
insert into m_lib_icpc_grouper values (467,"R80","INFLUENZA");
insert into m_lib_icpc_grouper values (468,"R81","PNEUMONIA");
insert into m_lib_icpc_grouper values (469,"R82","PLEURISY/PLEURAL EFFUSION");
insert into m_lib_icpc_grouper values (470,"R83","RESPIRATORY INFECTION, OTHER");
insert into m_lib_icpc_grouper values (471,"R84","MALIGNT NEOPLASM BRONC/ LUNG");
insert into m_lib_icpc_grouper values (472,"R85","MALIGNT NEOPLASM RESPIRATORY");
insert into m_lib_icpc_grouper values (473,"R86","BENIGN NEOPLASM RESPIRATORY");
insert into m_lib_icpc_grouper values (474,"R87","FOREIGN BODY IN NOSE/LARYNX/BR");
insert into m_lib_icpc_grouper values (475,"R88","INJURY RESPIRATORY, OTHER");
insert into m_lib_icpc_grouper values (476,"R89","CONGENITAL ANOM RESPIRATORY");
insert into m_lib_icpc_grouper values (477,"R90","HYPERTROPHY TONSILS/ADENOIDS");
insert into m_lib_icpc_grouper values (478,"R92","NEOPLASM UNCERTAIN REPIRATOR)");
insert into m_lib_icpc_grouper values (479,"R95","CHRONIC OBSTRUCTIVE PULMONARY");
insert into m_lib_icpc_grouper values (480,"R96","ASTHMA");
insert into m_lib_icpc_grouper values (481,"R97","ALLERGIC RHINITIS");
insert into m_lib_icpc_grouper values (482,"R98","HYPERVENTILATION SYNDROME");
insert into m_lib_icpc_grouper values (483,"R99","RESPIRATORY DISEASE, OTHER");
insert into m_lib_icpc_grouper values (484,"S01","PAIN, TENDERNESS OF SKIN");
insert into m_lib_icpc_grouper values (485,"S02","PRURITUS");
insert into m_lib_icpc_grouper values (486,"S03","WARTS");
insert into m_lib_icpc_grouper values (487,"S04","LUMP/SWELLING, LOCALISED");
insert into m_lib_icpc_grouper values (488,"S06","RASH LOCALIZED");
insert into m_lib_icpc_grouper values (489,"S07","RASH GENERALIZED");
insert into m_lib_icpc_grouper values (490,"S08","SKIN COLOR CHANGE");
insert into m_lib_icpc_grouper values (491,"S09","INFECTED FINGER/TOE");
insert into m_lib_icpc_grouper values (492,"S10","BOIL/CARBUNCLE");
insert into m_lib_icpc_grouper values (493,"S11","SKIN INFECTION, POST TRAUMATIC");
insert into m_lib_icpc_grouper values (494,"S12","INSECT BITE/STING");
insert into m_lib_icpc_grouper values (495,"S13","ANIMAL/HUMAN BITE");
insert into m_lib_icpc_grouper values (496,"S14","BURNS/SCALDS");
insert into m_lib_icpc_grouper values (497,"S15","FOREIGN BODY IN SKIN");
insert into m_lib_icpc_grouper values (498,"S16","BRUISE/CONTUSION");
insert into m_lib_icpc_grouper values (499,"S17","ABRASION/SCRATCH/BLISTER");
insert into m_lib_icpc_grouper values (500,"S18","LACERATION/CUT");
insert into m_lib_icpc_grouper values (501,"S19","INJURY SKIN, OTHER");
insert into m_lib_icpc_grouper values (502,"S20","CORNS/CALOSITIES");
insert into m_lib_icpc_grouper values (503,"S21","SKIN TEXTURE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (504,"S22","NAIL SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (505,"S23","HAIR LOSS/BALDN (INCL ALOPECIA)");
insert into m_lib_icpc_grouper values (506,"S24","HAIR/SCALP SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (507,"S26","FEAR, CANCER  SKIN");
insert into m_lib_icpc_grouper values (508,"S27","FEAR, SKIN DISEASE, OTHER");
insert into m_lib_icpc_grouper values (509,"S29","SKIN SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (510,"S30","MED EXAM/CHECK, FULL, SKIN");
insert into m_lib_icpc_grouper values (511,"S31","MED EXAM/CHECK, PART, SKIN");
insert into m_lib_icpc_grouper values (512,"S70","HERPES ZOSTER");
insert into m_lib_icpc_grouper values (513,"S71","HERPES SIMPLEX");
insert into m_lib_icpc_grouper values (514,"S72","SCABIES AND OTHER ACARIASES");
insert into m_lib_icpc_grouper values (515,"S73","PEDICULOSIS/SKIN INFESTATIONS,");
insert into m_lib_icpc_grouper values (516,"S74","DERMATOPHYTOSIS");
insert into m_lib_icpc_grouper values (517,"S75","MONILIASIS/CANDIDIASIS SKIN");
insert into m_lib_icpc_grouper values (518,"S76","SKIN INFECTION, OTHER");
insert into m_lib_icpc_grouper values (519,"S77","MALIGNT NEOPLASM SKIN");
insert into m_lib_icpc_grouper values (520,"S78","LIPOMA");
insert into m_lib_icpc_grouper values (521,"S79","BENIGN/UNCERT NEOPLASM SKIN");
insert into m_lib_icpc_grouper values (522,"S80","SOLAR KERATOSIS/SUNBURN");
insert into m_lib_icpc_grouper values (523,"S81","HAEMANGIOMA/LYMPHANGIOMA");
insert into m_lib_icpc_grouper values (524,"S82","NAEVUS/MOLE");
insert into m_lib_icpc_grouper values (525,"S83","CONGENITAL ANOM SKIN, OTHER");
insert into m_lib_icpc_grouper values (526,"S84","IMPETIGO");
insert into m_lib_icpc_grouper values (527,"S85","PILONIDAL CYST/FISTULA");
insert into m_lib_icpc_grouper values (528,"S86","DERMATITIS, SEBORRHOEIC");
insert into m_lib_icpc_grouper values (529,"S87","DERMATITIS, ATOPIC ECZEMA");
insert into m_lib_icpc_grouper values (530,"S88","DERMATITIS, CONTACT/ALLERGIC");
insert into m_lib_icpc_grouper values (531,"S89","DIAPER RASH");
insert into m_lib_icpc_grouper values (532,"S90","PITYRIASIS ROSEA");
insert into m_lib_icpc_grouper values (533,"S91","PSORIASIS");
insert into m_lib_icpc_grouper values (534,"S92","SWEAT GLAND DISEASE");
insert into m_lib_icpc_grouper values (535,"S93","SEBACEOUS CYST");
insert into m_lib_icpc_grouper values (536,"S94","INGROWING NAIL");
insert into m_lib_icpc_grouper values (537,"S95","MOLLUSCA CONTAGIOSUM");
insert into m_lib_icpc_grouper values (538,"S96","ACNE");
insert into m_lib_icpc_grouper values (539,"S97","CHRONIC ULCER SKIN (INCL VARICOSE");
insert into m_lib_icpc_grouper values (540,"S98","URTICARIA");
insert into m_lib_icpc_grouper values (541,"S99","SKIN DISEASE, OTHER");
insert into m_lib_icpc_grouper values (542,"T01","EXCESSIVE THIRST");
insert into m_lib_icpc_grouper values (543,"T02","EXCESSIVE APPETITE");
insert into m_lib_icpc_grouper values (544,"T03","LOSS OF APPETITE");
insert into m_lib_icpc_grouper values (545,"T04","FEEDING PROBLEM OF INFANT/CHIL");
insert into m_lib_icpc_grouper values (546,"T05","FEEDING PROBLEM OF ADULT");
insert into m_lib_icpc_grouper values (547,"T07","WEIGHT GAIN");
insert into m_lib_icpc_grouper values (548,"T08","WEIGHT LOSS");
insert into m_lib_icpc_grouper values (549,"T10","GROWTH DELAY");
insert into m_lib_icpc_grouper values (821,"T11","DEHYDRATION");
insert into m_lib_icpc_grouper values (550,"T26","FEAR, CANCER ENDOCRINE SYSTE");
insert into m_lib_icpc_grouper values (551,"T27","FEAR, ENDOCRINE/METABOLIC DI");
insert into m_lib_icpc_grouper values (552,"T29","ENDOCRINE/METAB/NUTRITION SYMP");
insert into m_lib_icpc_grouper values (553,"T30","MED EXAM/CHECK, FULL ENDO/METAB");
insert into m_lib_icpc_grouper values (554,"T31","MED EXAM/CHECK, PART, ENDOC/ME");
insert into m_lib_icpc_grouper values (555,"T70","ENDOCRINE INFECTION");
insert into m_lib_icpc_grouper values (556,"T71","MALIGNT NEOPLASM THYROID");
insert into m_lib_icpc_grouper values (557,"T72","BENIGN NEOPLASM THYROID");
insert into m_lib_icpc_grouper values (558,"T73","NEOPLASM ENDOCR, OTH/UNCERT");
insert into m_lib_icpc_grouper values (559,"T80","CONGEN ANOM ENDOCR/METABO");
insert into m_lib_icpc_grouper values (560,"T81","GOITRE");
insert into m_lib_icpc_grouper values (561,"T82","OBESITY (BMI > 30)");
insert into m_lib_icpc_grouper values (562,"T83","OVERWEIGHT (BMI < 30)");
insert into m_lib_icpc_grouper values (563,"T85","HYPERTHYROIDISM/THYROTOXICOSIS");
insert into m_lib_icpc_grouper values (564,"T86","HYPOTHYROIDISM/MYXOEDEMA");
insert into m_lib_icpc_grouper values (565,"T87","HYPOGLYCEMIA");
insert into m_lib_icpc_grouper values (566,"T89","DIABETES, INSULIN DEPENDENT");
insert into m_lib_icpc_grouper values (567,"T90","DIABETES, NON-INSULIN DEPENDEN");
insert into m_lib_icpc_grouper values (568,"T91","VITAMIN/NUTRITIONAL DEFICIENCY");
insert into m_lib_icpc_grouper values (759,"T92","GOUT");
insert into m_lib_icpc_grouper values (569,"T93","LIPID DISORDER");
insert into m_lib_icpc_grouper values (570,"T99","ENDOCRINE/METABOLIC/NUTRITIONA");
insert into m_lib_icpc_grouper values (571,"U01","DYSURIA/PAINFUL URINATION");
insert into m_lib_icpc_grouper values (572,"U02","URINARY FREQUENCY/URGENCY");
insert into m_lib_icpc_grouper values (573,"U04","INCONTINENCE, URINE");
insert into m_lib_icpc_grouper values (574,"U05","URINATION PROBLEMS, OTHER");
insert into m_lib_icpc_grouper values (575,"U06","HAEMATURIA");
insert into m_lib_icpc_grouper values (576,"U07","URINE COMPLAINTS, OTHER");
insert into m_lib_icpc_grouper values (822,"U08","URINARY RETENTION");
insert into m_lib_icpc_grouper values (577,"U13","BLADDER SYMPT/COMPL, OTHER");
insert into m_lib_icpc_grouper values (578,"U14","KIDNEY SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (823,"U26","FEAR OF CANCER OF URINARY SYSTEM");
insert into m_lib_icpc_grouper values (824,"U27","FEAR OF URINARY DISEASE OTHER");
insert into m_lib_icpc_grouper values (579,"U28","LIMITED FUNCTN/DISABIL URINARY");
insert into m_lib_icpc_grouper values (580,"U29","URINARY SYMPT/COMPLAINT, OTH");
insert into m_lib_icpc_grouper values (581,"U30","MED EXAM/CHECK, FULL, URINARY");
insert into m_lib_icpc_grouper values (582,"U31","MED EXAM/CHECK, PART, URINARY");
insert into m_lib_icpc_grouper values (583,"U70","PYELONEPHRITIS/PYELITIS");
insert into m_lib_icpc_grouper values (584,"U71","CYSTITIS/URIN INFECTION, OTHER");
insert into m_lib_icpc_grouper values (585,"U72","URETHRITIS");
insert into m_lib_icpc_grouper values (586,"U75","MALIGNT NEOPLASM KIDNEY");
insert into m_lib_icpc_grouper values (587,"U76","MALIGNT NEOPLASM BLADDER");
insert into m_lib_icpc_grouper values (588,"U77","MALIGNT NEOPLASM URINARY, OTH");
insert into m_lib_icpc_grouper values (589,"U78","BENIGN NEOPLASM URINARY TRACT");
insert into m_lib_icpc_grouper values (590,"U79","NEOPLASM URINARY TRACT NOS");
insert into m_lib_icpc_grouper values (591,"U80","INJURY URINARY TRACT");
insert into m_lib_icpc_grouper values (592,"U85","CONGENITAL ANOM URIN TRACT");
insert into m_lib_icpc_grouper values (593,"U88","GLOMERULONEPHRITIS/NEPHROSIS");
insert into m_lib_icpc_grouper values (594,"U90","ORTHOSTATIC ALBUMINURIA/PROTEIORTHOSTATIC");
insert into m_lib_icpc_grouper values (595,"U95","URINARY CALCULUS");
insert into m_lib_icpc_grouper values (596,"U98","ABNORMAL URINE TEST NOS");
insert into m_lib_icpc_grouper values (597,"U99","URINARY DISEASE, OTHER");
insert into m_lib_icpc_grouper values (598,"W01","QUESTION OF PREGNANCY");
insert into m_lib_icpc_grouper values (599,"W02","FEAR, PREGNANCY");
insert into m_lib_icpc_grouper values (600,"W03","ANTEPARTUM BLEEDING");
insert into m_lib_icpc_grouper values (601,"W05","PREGNANCY NAUSEA/VOMITING");
insert into m_lib_icpc_grouper values (602,"W10","CONTRACEPTION, POSTCOITAL");
insert into m_lib_icpc_grouper values (603,"W11","CONTRACEPTION, ORAL");
insert into m_lib_icpc_grouper values (604,"W12","CONTRACEPTION, INTRAUTERINE");
insert into m_lib_icpc_grouper values (605,"W13","STERILIZATION (F)");
insert into m_lib_icpc_grouper values (606,"W14","CONTRACEPTION, OTHER");
insert into m_lib_icpc_grouper values (607,"W15","INFERTILITY/SUBFERTILITY (F)");
insert into m_lib_icpc_grouper values (608,"W17","POST PARTUM BLEEDING");
insert into m_lib_icpc_grouper values (609,"W18","POST PARTUM SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (610,"W19","BREAST/LACTATION SYMPT/COMPL, OTHER (F)");
insert into m_lib_icpc_grouper values (611,"W21","CONCERN, BODY IMAGE RELAT");
insert into m_lib_icpc_grouper values (612,"W27","FEAR, COMPLICATIONS OF PREGN");
insert into m_lib_icpc_grouper values (613,"W28","LIMITED FUNCTN/DISABIL PREGNA");
insert into m_lib_icpc_grouper values (614,"W29","PREGNANCY SYMPT/COMPL, OTH");
insert into m_lib_icpc_grouper values (615,"W30","MED EXAM/CHECK, FULL, PREG/FP");
insert into m_lib_icpc_grouper values (616,"W31","MED EXAM/CHECK, PART, PREG/FP");
insert into m_lib_icpc_grouper values (617,"W70","PUERPERAL INFECTION/SEPSIS");
insert into m_lib_icpc_grouper values (618,"W71","INFECTION COMPLICAT PREGNAN");
insert into m_lib_icpc_grouper values (619,"W72","MALIGNT NEOPLASM IN PREGNANCY");
insert into m_lib_icpc_grouper values (620,"W73","BENIGN/UNCERT NEOPL IN PREGNANC");
insert into m_lib_icpc_grouper values (621,"W75","INJURY COMPLICATING PREGNANCY");
insert into m_lib_icpc_grouper values (622,"W76","CONGEN ANOM COMPLICAT PREG");
insert into m_lib_icpc_grouper values (623,"W78","PREGNANCY");
insert into m_lib_icpc_grouper values (624,"W79","UNWANTED PREGNANCY");
insert into m_lib_icpc_grouper values (625,"W80","ECTOPIC PREGNANCY");
insert into m_lib_icpc_grouper values (626,"W81","TOXAEMIA OF PREGNANCY");
insert into m_lib_icpc_grouper values (627,"W82","ABORTION, SPONTANEOUS");
insert into m_lib_icpc_grouper values (628,"W83","ABORTION, INDUCED");
insert into m_lib_icpc_grouper values (629,"W84","PREGNANCY HIGH RISK");
insert into m_lib_icpc_grouper values (630,"W85","GESTATIONAL DIABETES");
insert into m_lib_icpc_grouper values (631,"W90","UNCOMPLICATE DELIVER, LIVEBIRT");
insert into m_lib_icpc_grouper values (632,"W91","UNCOMPLICATE DELIVER, STILLBIRT");
insert into m_lib_icpc_grouper values (633,"W92","COMPLICATE DELIVERY, LIVEBIRTH");
insert into m_lib_icpc_grouper values (634,"W93","COMPLICATE DELIVERY, STILLBIRT");
insert into m_lib_icpc_grouper values (635,"W94","PUERPERAL MASTITIS");
insert into m_lib_icpc_grouper values (636,"W95","BREAST DISORDER IN PREG/PUERPER");
insert into m_lib_icpc_grouper values (637,"W96","COMPLICATE,  PUERPERIUM, OTHE");
insert into m_lib_icpc_grouper values (638,"W99","DISORDERS, PREGNANCY/DELIVER");
insert into m_lib_icpc_grouper values (639,"X01","PAIN, GENITAL (F)");
insert into m_lib_icpc_grouper values (640,"X02","PAIN, MENSTRUAL");
insert into m_lib_icpc_grouper values (641,"X03","PAIN, INTERMENSTRUAL");
insert into m_lib_icpc_grouper values (642,"X04","PAINFUL INTERCOURSE (F)");
insert into m_lib_icpc_grouper values (643,"X05","MENSTRUATION ABSENT/SCANTY");
insert into m_lib_icpc_grouper values (644,"X06","MENSTRUATION EXCESSIVE");
insert into m_lib_icpc_grouper values (645,"X07","MENSTRUATION IRREGULAR/FREQUEN");
insert into m_lib_icpc_grouper values (646,"X08","INTERMENSTRUAL BLEEDING");
insert into m_lib_icpc_grouper values (647,"X09","PREMENSTRUAL SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (648,"X10","POSTPONE  MENSTRUATION");
insert into m_lib_icpc_grouper values (649,"X11","MENOPAUSAL SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (650,"X12","POSTMENOPAUSAL BLEEDING");
insert into m_lib_icpc_grouper values (651,"X13","POSTCOITAL BLEEDING");
insert into m_lib_icpc_grouper values (652,"X14","VAGINAL DISCHARGE");
insert into m_lib_icpc_grouper values (653,"X15","VAGINAL SYMPT/COMPLAINT, OTH");
insert into m_lib_icpc_grouper values (654,"X16","VULVAL SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (655,"X17","PELVIS SYMPT/COMPLAINT (F)");
insert into m_lib_icpc_grouper values (656,"X18","PAIN, BREAST (F)");
insert into m_lib_icpc_grouper values (657,"X19","BREAST LUMP/MASS (F)");
insert into m_lib_icpc_grouper values (658,"X20","NIPPLE SYMPT/COMPLAINT(F)");
insert into m_lib_icpc_grouper values (659,"X21","BREAST SYMPT/COMPL, OTHER (F)");
insert into m_lib_icpc_grouper values (660,"X22","CONCERN, BREAST APPEARANCE");
insert into m_lib_icpc_grouper values (661,"X23","FEAR, SEXUALLY TRANSMITTED DISEASE (F)");
insert into m_lib_icpc_grouper values (662,"X24","FEAR, SEXUAL DYSFUNCTION (F)");
insert into m_lib_icpc_grouper values (663,"X25","FEAR, CANCER GENITAL (F)");
insert into m_lib_icpc_grouper values (664,"X26","FEAR, CANCER BREAST(F)");
insert into m_lib_icpc_grouper values (665,"X27","FEAR, GENITAL/BREAST DISEASE");
insert into m_lib_icpc_grouper values (666,"X28","LIMITED FUNCTN/DISABIL GENIT (F)");
insert into m_lib_icpc_grouper values (667,"X29","GENITAL SYMPT/COMP, OTH (F)");
insert into m_lib_icpc_grouper values (668,"X30","MED EXAM/CHECK, FULL, GENIT (F)");
insert into m_lib_icpc_grouper values (669,"X31","MED EXAM/CHECK,PART,GENITO (F)");
insert into m_lib_icpc_grouper values (670,"X37","CYTOLOGY ( F)");
insert into m_lib_icpc_grouper values (671,"X70","SYPHILIS (F)");
insert into m_lib_icpc_grouper values (672,"X71","GONORRHOEA (F)");
insert into m_lib_icpc_grouper values (673,"X72","GENITAL CANDIDIASIS (F)");
insert into m_lib_icpc_grouper values (674,"X73","GENITAL TRICHOMONIASIS (F)");
insert into m_lib_icpc_grouper values (675,"X74","PELVIC INFLAMMATORY DISEASE");
insert into m_lib_icpc_grouper values (676,"X75","MALIGNT NEOPLASM CERVIX");
insert into m_lib_icpc_grouper values (677,"X76","MALIGNT NEOPLASM BREAST (F)");
insert into m_lib_icpc_grouper values (678,"X77","MALIGNANT NEOPLASM GENITAL OTHER (F)");
insert into m_lib_icpc_grouper values (679,"X78","FIBROMYOMA UTERUS");
insert into m_lib_icpc_grouper values (680,"X79","BENIGN NEOPLASM BREAST (F)");
insert into m_lib_icpc_grouper values (681,"X80","BENIGN NEOPLASM GENITAL (F)");
insert into m_lib_icpc_grouper values (682,"X81","NEOPLASM UNCERTAIN GENITAL (F)");
insert into m_lib_icpc_grouper values (683,"X82","INJURY GENITAL (F)");
insert into m_lib_icpc_grouper values (684,"X83","CONGENITAL ANOM GENITAL (F)");
insert into m_lib_icpc_grouper values (685,"X84","VAGINITIS/VULVITIS NOS");
insert into m_lib_icpc_grouper values (686,"X85","CERVICAL DISEASE NOS");
insert into m_lib_icpc_grouper values (687,"X86","ABNORMAL PAP SMEAR");
insert into m_lib_icpc_grouper values (688,"X87","UTEROVAGINAL PROLAPSE");
insert into m_lib_icpc_grouper values (689,"X88","FIBROCYSTIC DISEASE BREAST");
insert into m_lib_icpc_grouper values (690,"X89","PREMENSTRUAL TENSION SYNDROME");
insert into m_lib_icpc_grouper values (691,"X90","GENITAL HERPES (F)");
insert into m_lib_icpc_grouper values (692,"X91","CONDYLOMATA ACUMINATA (F)");
insert into m_lib_icpc_grouper values (693,"X92","CHLAMYDIA INFECTION, GENITAL (F))");
insert into m_lib_icpc_grouper values (694,"X99","GENITAL DISEASE, OTHER (F)");
insert into m_lib_icpc_grouper values (695,"Y01","PAIN, PENIS");
insert into m_lib_icpc_grouper values (696,"Y02","PAIN, TESTIS/SCROTUM");
insert into m_lib_icpc_grouper values (697,"Y03","URETHRAL DISCHARGE (M)");
insert into m_lib_icpc_grouper values (698,"Y04","PENIS SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (699,"Y05","SCROTUM/TESTIS SYMPT/COMPLAI");
insert into m_lib_icpc_grouper values (700,"Y06","PROSTATE SYMPT/COMPLAINT");
insert into m_lib_icpc_grouper values (701,"Y07","IMPOTENCE NOS");
insert into m_lib_icpc_grouper values (702,"Y08","SEXUAL FUNCTN SYMPT/COMPLA");
insert into m_lib_icpc_grouper values (703,"Y10","INFERTILITY/SUBFERTILITY (M)");
insert into m_lib_icpc_grouper values (704,"Y13","STERILISATION (M)");
insert into m_lib_icpc_grouper values (705,"Y14","FAMILY PLANNING, OTHER (M)");
insert into m_lib_icpc_grouper values (706,"Y16","BREAST SYMPT/COMPL (M)");
insert into m_lib_icpc_grouper values (707,"Y24","FEAR, SEXUAL DYSFUNCTION (M)");
insert into m_lib_icpc_grouper values (708,"Y25","FEAR, SEXUALLY TRANSMITTED DISEASE (M)");
insert into m_lib_icpc_grouper values (709,"Y26","FEAR, CANCER GENITAL (M)");
insert into m_lib_icpc_grouper values (710,"Y27","FEAR, GENITAL DISEASE, OTHER");
insert into m_lib_icpc_grouper values (711,"Y28","LIMITED FUNCTN/DISABIL GENITAL (M)");
insert into m_lib_icpc_grouper values (712,"Y29","GENITAL SYMPT/COMPLAINT, OTH (M)");
insert into m_lib_icpc_grouper values (713,"Y30","MED EXAM/CHECK, FULL, GENIT (M)");
insert into m_lib_icpc_grouper values (714,"Y31","MED EXAM/CHECK,PART,GENITO (M)");
insert into m_lib_icpc_grouper values (715,"Y70","SYPHILIS (M)");
insert into m_lib_icpc_grouper values (716,"Y71","GONORRHOEA (MA)");
insert into m_lib_icpc_grouper values (825,"Y72","GENITAL HERPES MALE");
insert into m_lib_icpc_grouper values (717,"Y73","PROSTATITIS/SEMINAL VESICULITI");
insert into m_lib_icpc_grouper values (718,"Y74","ORCHITIS/EPIDIDYMITIS");
insert into m_lib_icpc_grouper values (719,"Y75","BALANITIS");
insert into m_lib_icpc_grouper values (720,"Y76","CONDYLOMATA ACUMINATA (M)");
insert into m_lib_icpc_grouper values (721,"Y77","MALIGNT NEOPLASM PROSTATE");
insert into m_lib_icpc_grouper values (722,"Y78","MALIGNANT NEOPLASM GENITAL OTHER (M)");
insert into m_lib_icpc_grouper values (723,"Y79","BENIGN/UNCERT NEOPL MALE GENITA");
insert into m_lib_icpc_grouper values (724,"Y80","INJURY GENITAL (M)");
insert into m_lib_icpc_grouper values (725,"Y81","PHIMOSIS/REDUNDANT PREPUCE");
insert into m_lib_icpc_grouper values (726,"Y82","HYPOSPADIA");
insert into m_lib_icpc_grouper values (727,"Y83","UNDESCENDED TESTICLE");
insert into m_lib_icpc_grouper values (728,"Y84","CONGENITAL ANOM GENITAL (M)");
insert into m_lib_icpc_grouper values (729,"Y85","BENIGN PROSTATIC HYPERTROPHY");
insert into m_lib_icpc_grouper values (730,"Y86","HYDROCOELE");
insert into m_lib_icpc_grouper values (731,"Y99","GENITAL DISEASE, OTHER (M)");
insert into m_lib_icpc_grouper values (732,"Z01","POVERTY/FINANCIAL PROBLEM");
insert into m_lib_icpc_grouper values (733,"Z02","FOOD AND WATER PROBLEM");
insert into m_lib_icpc_grouper values (734,"Z03","HOUSING/NEIGHBORHOOD PROBLEM");
insert into m_lib_icpc_grouper values (735,"Z04","SOCIAL CULTURAL PROBLEM");
insert into m_lib_icpc_grouper values (736,"Z05","WORK PROBLEM");
insert into m_lib_icpc_grouper values (737,"Z06","UNEMPLOYMENT PROBLEM");
insert into m_lib_icpc_grouper values (738,"Z07","EDUCATION PROBLEM");
insert into m_lib_icpc_grouper values (739,"Z08","SOCIAL WELFARE PROBLEM");
insert into m_lib_icpc_grouper values (740,"Z09","LEGAL PROBLEM");
insert into m_lib_icpc_grouper values (741,"Z10","HEALTH CARE SYSTEM PROBLEM");
insert into m_lib_icpc_grouper values (742,"Z11","COMPLIANCE/BEING ILL PROBLEM");
insert into m_lib_icpc_grouper values (743,"Z12","RELATIONSHIP PROBLEM, PARTNERS");
insert into m_lib_icpc_grouper values (744,"Z13","PARTNER BEHAVIOUR PROBLEM");
insert into m_lib_icpc_grouper values (745,"Z14","PARTNER ILLNESS PROBLEM");
insert into m_lib_icpc_grouper values (746,"Z15","LOSS/DEATH, PARTNER");
insert into m_lib_icpc_grouper values (747,"Z16","RELATIONSHIP PROBLEM, CHILD");
insert into m_lib_icpc_grouper values (748,"Z18","ILLNESS PROBLEM WITH CHILD");
insert into m_lib_icpc_grouper values (749,"Z19","LOSS/DEATH, CHILD");
insert into m_lib_icpc_grouper values (750,"Z20","RELATIONSHIP PROBLEM, PARENT/F");
insert into m_lib_icpc_grouper values (751,"Z21","BEHAVIOR PROBLEM, PARENT/FAMIL");
insert into m_lib_icpc_grouper values (752,"Z22","ILLNESS PROBLEM, PARENT/FAMILY");
insert into m_lib_icpc_grouper values (753,"Z23","LOSS/DEATH, PARENT/FAM MEMB");
insert into m_lib_icpc_grouper values (754,"Z24","RELATIONSHIP PROBLEM, FRIENDS");
insert into m_lib_icpc_grouper values (755,"Z25","ASSAULT/HARMFUL EVENT");
insert into m_lib_icpc_grouper values (756,"Z27","FEAR, SOCIAL PROBLEM");
insert into m_lib_icpc_grouper values (757,"Z28","SOCIAL HANDICAP");
insert into m_lib_icpc_grouper values (758,"Z29","SOCIAL PROBLEM NOS");
